const India = {
  states: ["Delhi", "Maharastra", "Uttar Pradesh", "Haryana", "Punjab"],
  countryCode: "+91",
  femaleNames: ["priyanka", "divya", "manu"],
  maleNames: ["praveen", "lalit", "monu"],
  surnames: [
    "Kumar",
    "Prajapati",
    "Gupta",
    "Pratap",
    "Chawdhary",
    "Malhotra",
    "Sharma",
    "Shukla",
  ],
  carCompanies: [
    "Maruti Suzuki",
    "Hyundai",
    "Tata Motors",
    "Mahindra & Mahindra",
    "Honda",
    "Toyota",
    "Ford",
    "Renault",
    "Volkswagen",
    "Skoda",
    "Mercedes-Benz",
    "BMW",
    "Audi",
    "Nissan",
    "Kia",
    "Volvo",
    "Jaguar",
    "Land Rover",
    "Mitsubishi",
    "Chevrolet",
  ],
  cards: ["Visa", "Mastercard", "Rupay", "Discover"],
  companies: [
    "Tata",
    "Google",
    "Facebook",
    "Apple",
    "Ola",
    "Jio",
    "Zoomato",
    "Uber",
    "BSNL",
    "Mintra",
    "Flipkart",
    "Amazon",
    "Lenskart",
  ],
};

const America = {
  states: ["Delhi", "Maharastra", "Uttar Pradesh", "Haryana", "Punjab"],
  countryCode: "+91",
  femaleNames: ["priyanka", "divya", "manu"],
  maleNames: ["praveen", "lalit", "monu"],
  surnames: [
    "Kumar",
    "Prajapati",
    "Gupta",
    "Pratap",
    "Chawdhary",
    "Malhotra",
    "Sharma",
    "Shukla",
  ],
  carCompanies: [
    "Ford",
    "Chevrolet",
    "Dodge",
    "Jeep",
    "Tesla",
    "Cadillac",
    "GMC",
    "Chrysler",
    "Buick",
    "Chevrolet",
    "Lincoln",
    "Ram",
    "Acura",
    "Infiniti",
    "Mercedes-Benz",
    "BMW",
    "Audi",
    "Chevrolet",
    "Nissan",
    "Toyota",
  ],
  cards: ["Visa", "Mastercard", "Rupay", "Discover"],
  companies: [
    "Tata",
    "Google",
    "Facebook",
    "Apple",
    "Ola",
    "Jio",
    "Zoomato",
    "Uber",
    "BSNL",
    "Mintra",
    "Flipkart",
    "Amazon",
    "Lenskart",
  ],
};

const Japan = {
  name: "Japan",
  countryCode: "JP",
  currency: "yen",
  language: "Japanese",
  states: [
    {
      name: "Hokkaido",
      cities: [
        "Sapporo",
        "Hakodate",
        "Asahikawa",
        "Obihiro",
        "Kitami",
        "Abashiri",
        "Kushiro",
        "Muroran",
        "Tomakomai",
        "Wakkanai",
      ],
    },
    {
      name: "Aomori",
      cities: [
        "Aomori",
        "Hachinohe",
        "Hirosaki",
        "Misawa",
        "Mutsu",
        "Towada",
        "Goshogawara",
        "Namioka",
        "Odate",
        "Tsuruta",
      ],
    },
    {
      name: "Iwate",
      cities: [
        "Morioka",
        "Hanamaki",
        "Kitakami",
        "Tono",
        "Kamaishi",
        "Takizawa",
        "Ichinoseki",
        "Oshu",
        "Ninohe",
        "Miyako",
      ],
    },
    {
      name: "Miyagi",
      cities: [
        "Sendai",
        "Ishinomaki",
        "Tagajo",
        "Shiogama",
        "Furukawa",
        "Osaki",
        "Higashimatsushima",
        "Kakuda",
        "Shiroishi",
        "Kurihara",
      ],
    },
    {
      name: "Akita",
      cities: [
        "Akita",
        "Yokote",
        "Noshiro",
        "Odate",
        "Oga",
        "Kosaka",
        "Kazuno",
        "Kakunodate",
        "Yuzawa",
        "Katagami",
      ],
    },
    {
      name: "Yamagata",
      cities: [
        "Yamagata",
        "Sakata",
        "Tsuruoka",
        "Yonezawa",
        "Shinjo",
        "Sagae",
        "Higashine",
        "Murayama",
        "Obanazawa",
        "Nanyo",
      ],
    },
    {
      name: "Fukushima",
      cities: [
        "Fukushima",
        "Koriyama",
        "Iwaki",
        "Shirakawa",
        "Nihonmatsu",
        "Soma",
        "Date",
        "Futaba",
        "Miharu",
        "Tamakawa",
      ],
    },
    {
      name: "Ibaraki",
      cities: [
        "Mito",
        "Hitachi",
        "Tsuchiura",
        "Tsukuba",
        "Koga",
        "Kasama",
        "Naka",
        "Moriya",
        "Toride",
        "Ryugasaki",
      ],
    },
    {
      name: "Tochigi",
      cities: [
        "Utsunomiya",
        "Ashikaga",
        "Kanuma",
        "Sano",
        "Otawara",
        "Nikko",
        "Nasu",
        "Takahagi",
        "Mooka",
        "Tochigi",
      ],
    },
    {
      name: "Gunma",
      cities: [
        "Maebashi",
        "Takasaki",
        "Ota",
        "Isesaki",
        "Kiryu",
        "Numata",
        "Tatebayashi",
        "Fujioka",
        "Annaka",
        "Tomioka",
      ],
    },
    {
      name: "Saitama",
      cities: [
        "Saitama",
        "Kawaguchi",
        "Kawagoe",
        "Koshigaya",
        "Tokorozawa",
        "Kasukabe",
        "Sayama",
        "Iruma",
        "Fujimi",
        "Yashio",
      ],
    },
  ],
  phoneCode: "+81",
  femaleNames: [
    "Ayumi",
    "Haruka",
    "Yui",
    "Miyuki",
    "Sakura",
    "Rina",
    "Yuna",
    "Ami",
    "Akari",
    "Hina",
    "Misaki",
    "Airi",
    "Nana",
    "Mayu",
    "Aya",
    "Risa",
    "Yuka",
    "Yuko",
    "Mika",
    "Rika",
    "Mana",
    "Yuri",
    "Erika",
    "Kaori",
    "Maiko",
    "Emi",
    "Megumi",
    "Nami",
    "Natsumi",
    "Konomi",
    "Kana",
    "Miho",
    "Yoko",
    "Mei",
    "Nozomi",
    "Saki",
    "Mizuki",
    "Marina",
    "Tomoko",
    "Asuka",
    "Kotone",
    "Mio",
    "Hinata",
    "Yumi",
    "Rie",
    "Ayaka",
    "Sayaka",
    "Eri",
    "Maki",
    "Satomi",
  ],
  maleNames: [
    "Hiroshi",
    "Kazuki",
    "Takashi",
    "Yukihiro",
    "Ryo",
    "Masato",
    "Satoshi",
    "Naoki",
    "Haruki",
    "Yusuke",
    "Tatsuya",
    "Kota",
    "Daiki",
    "Kaito",
    "Kengo",
    "Shota",
    "Daisuke",
    "Yuto",
    "Kenji",
    "Riku",
    "Sho",
    "Ryota",
    "Keisuke",
    "Takeru",
    "Yoshihiro",
    "Tomoaki",
    "Sota",
    "Sora",
    "Takumi",
    "Taichi",
    "Hayato",
    "Kazuya",
    "Koki",
    "Kazuki",
    "Takahiro",
    "Akihiro",
    "Hikaru",
    "Haru",
    "Kosuke",
    "Hiroki",
    "Ryusei",
    "Kazuma",
    "Akira",
    "Yuji",
    "Shinichi",
    "Toshiro",
    "Yoshio",
    "Eiji",
    "Isamu",
    "Junichi",
  ],
  surnames: [
    "Sato",
    "Suzuki",
    "Takahashi",
    "Tanaka",
    "Watanabe",
    "Ito",
    "Yamamoto",
    "Nakamura",
    "Kobayashi",
    "Kato",
    "Yoshida",
    "Yamada",
    "Sasaki",
    "Yamaguchi",
    "Matsumoto",
    "Inoue",
    "Kimura",
    "Hayashi",
    "Shimizu",
    "Saito",
    "Saito",
    "Ishikawa",
    "Sakamoto",
    "Aoki",
    "Fujita",
    "Ogawa",
    "Okada",
    "Hasegawa",
    "Murakami",
    "Kondo",
    "Ishii",
    "Fujii",
    "Tamura",
    "Nishimura",
    "Matsuda",
    "Ota",
    "Takagi",
    "Nakagawa",
    "Sugiyama",
    "Hirano",
    "Tsuruoka",
    "Tajima",
    "Araki",
    "Mori",
    "Miyazaki",
    "Ueda",
    "Shibata",
    "Saito",
    "Nakayama",
    "Abe",
    "Kojima",
  ],
  carCompanies: [
    "Toyota",
    "Honda",
    "Nissan",
    "Mazda",
    "Subaru",
    "Suzuki",
    "Mitsubishi",
    "Lexus",
    "Infiniti",
    "Acura",
    "Daihatsu",
    "Isuzu",
    "Mitsubishi",
    "Mazda",
    "Subaru",
    "Nissan",
    "Nissan",
    "Suzuki",
    "Toyota",
    "Honda",
  ],
  cards: ["Visa", "Mastercard", "Rupay", "Discover"],
  companies: [
    "Toyota Motor Corporation 🚗",
    "Sony 📺",
    "Nintendo 🎮",
    "Honda Motor Co., Ltd. 🚗",
    "Panasonic Corporation 📷",
    "Canon Inc. 📸",
    "Nissan Motor Co., Ltd. 🚗",
    "Mitsubishi Corporation 🏢",
    "Toshiba Corporation 💻",
    "Mazda Motor Corporation 🚗",
    "Hitachi, Ltd. ⚡",
    "Sumitomo Mitsui Financial Group 🏦",
    "SoftBank Group Corp. 📱",
    "Subaru Corporation 🚗",
    "Takeda Pharmaceutical Company Limited 💊",
    "Kawasaki Heavy Industries, Ltd. 🏗️",
    "Nippon Steel Corporation 🏭",
    "Rakuten, Inc. 🛒",
    "Mitsui & Co., Ltd. 🏭",
    "Suzuki Motor Corporation 🏍️",
    "Yamaha Corporation 🎵",
    "Itochu Corporation 🛍️",
    "Denso Corporation 🚗",
    "Fujitsu Limited 💻",
    "Shiseido Company, Limited 💄",
    "Mitsubishi Electric Corporation ⚡",
    "ORIX Corporation 🏦",
    "ANA Holdings Inc. ✈️",
    "East Japan Railway Company 🚆",
    "KDDI Corporation 📞",
    "Nippon Telegraph and Telephone Corporation 📞",
    "Bridgestone Corporation 🚗",
    "Seven & I Holdings Co., Ltd. 🏪",
    "Mitsubishi UFJ Financial Group 🏦",
    "Kao Corporation 🛀",
    "Daikin Industries, Ltd. ❄️",
    "LIXIL Group Corporation 🏠",
    "Shin-Etsu Chemical Co., Ltd. 🧪",
    "Konica Minolta, Inc. 🖨️",
    "Asahi Group Holdings, Ltd. 🍻",
    "Kobe Steel, Ltd. 🏭",
    "Tokio Marine Holdings, Inc. 🏦",
    "Mizuho Financial Group, Inc. 🏦",
  ],
};

const Professions = [
  "Software Engineer",
  "Data Analyst",
  "Product Manager",
  "Marketing Specialist",
  "Financial Analyst",
  "Sales Representative",
  "Human Resources Manager",
  "Graphic Designer",
  "Operations Manager",
  "Customer Support Specialist",
  "Business Development Executive",
  "Content Writer",
  "Quality Assurance Tester",
  "UI/UX Designer",
  "Research Scientist",
  "Project Manager",
  "Data Scientist",
  "Web Developer",
  "Network Administrator",
  "IT Consultant",
  "Financial Advisor",
  "Social Media Manager",
  "Market Research Analyst",
  "Supply Chain Manager",
  "Digital Marketing Manager",
  "Systems Engineer",
  "Mobile App Developer",
  "Technical Support Engineer",
  "Accountant",
  "Business Analyst",
  "Software Architect",
  "Public Relations Manager",
  "UX Researcher",
  "Cybersecurity Analyst",
  "Operations Analyst",
  "Content Strategist",
  "Data Engineer",
  "Sales Manager",
  "Customer Success Manager",
  "UX/UI Manager",
  "Network Engineer",
  "Digital Strategist",
];
const Colors = [
  "red",
  "blue",
  "green",
  "yellow",
  "purple",
  "pink",
  "orange",
  "brown",
  "black",
  "white",
  "gray",
  "silver",
  "gold",
  "maroon",
  "teal",
  "navy",
  "olive",
  "lime",
  "aqua",
  "coral",
  "indigo",
  "violet",
  "magenta",
  "salmon",
  "turquoise",
  "lavender",
  "khaki",
  "beige",
  "peach",
  "plum",
  "skyblue",
  "chocolate",
  "ivory",
  "saddlebrown",
  "firebrick",
  "peru",
  "rosybrown",
  "sienna",
  "slategray",
  "tomato",
  "wheat",
];
const TempMail = ["teleworm.us", "cuvox.de", "dayrop.com", "einrot.com"];
const Gender = ["female", "male"];
const TLD = [
  "store",
  "online",
  "tk",
  "uk",
  "com",
  "org",
  "info",
  "io",
  "ai",
  "dev",
  "in",
  "jp",
  "co.in",
  "co.jp",
];

const Month = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const Agent = {
  browsers: [
    "Chrome",
    "Firefox",
    "Safari",
    "Opera",
    "Edge",
    "Internet Explorer",
  ],

  os: [
    "Windows NT 10.0",
    "Windows NT 6.1",
    "Macintosh; Intel Mac OS X 10_14_5",
    "Macintosh; Intel Mac OS X 10_13_6",
    "Linux x86_64",
  ],

  userAgentStrings: [
    "Mozilla/5.0 ({os}) AppleWebKit/537.36 (KHTML, like Gecko) {browser}/75.0.3770.100 Safari/537.36",
    "Mozilla/5.0 ({os}) AppleWebKit/537.36 (KHTML, like Gecko) {browser}/83.0.4103.61 Safari/537.36",
    "Mozilla/5.0 ({os}) AppleWebKit/537.36 (KHTML, like Gecko) {browser}/89.0.4389.82 Safari/537.36",
    "Mozilla/5.0 ({os}) AppleWebKit/537.36 (KHTML, like Gecko) {browser}/70.0.3538.102 Safari/537.36",
    "Mozilla/5.0 ({os}) AppleWebKit/537.36 (KHTML, like Gecko) {browser}/92.0.4515.131 Safari/537.36",
  ],
};

const BloodType = ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"];

export {
  America,
  India,
  Professions,
  Colors,
  TempMail,
  Japan,
  Gender,
  TLD,
  Month,
  BloodType,
  Agent,
};
